# Generated by Django 5.2.1 on 2025-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollvote',
            name='channel_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
